# Introduction to PyTorch

The debut of Pytorch

What is the Torch python package?   A Torch!

As for **PyTorch**, it is a version of the **Torch** library for Python programming which is immensely popular for its flexibility, speed, and seamless compatibility with the Python ecosystem. 

It allows developers to perform computations on Tensors, which are high-dimensional arrays, similar to the ndarray in Numpy. The significant advantage of PyTorch Tensors over **Numpy ndarrays** is that PyTorch Tensors can utilize GPUs to **accelerate their numeric computations**.

TensorFlow, on the other hand, is another highly popular framework known for providing comprehensive, flexible ecosystems of tools, libraries, and community resources to researchers pushing the state-of-the-art in Machine Learning, or developers who want to build and deploy Machine Learning applications.

![title](./img/1.png)

## ## The Rapid Development of PyTorch

    Is the framework easy to use? Let's see what the figure below showed!


![title](./img/3.png)

![title](./img/4.png)

PyTorch has indeed made a significant impact since its debut, making it one of the primary tools for developing deep learning models today.

In the past, Caffe had been the predominant deep learning framework until the end of 2015, largely due to its efficiency.

However, TensorFlow emerged and quickly rose to prominence thanks to its flexible, versatile, and comprehensive nature. For several years, it has been the preferred choice for many in both academic and industry settings.

Yet, since 2019, PyTorch has been gradually gaining more recognition and usage in both academia and industry. It has been celebrated for its user-friendly interface and simplicity, which makes the implementation of deep learning models run smoother. And thus, PyTorch successfully won over a large chunk of the deep learning community.
The constant growth and competition between these frameworks indicate the dynamic and ever-evolving nature of the field of deep learning. Such competition also promotes advancements and improvements in the tools we use, ultimately benefiting the developers and researchers in the field.

### Installing PyTorch: The method using PIP is relatively simple.

the CPU version of PyTorch：pip install torch==1.3.0+cpu torchvision==0.4.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

the GPU version of PyTorch：pip install torch===1.3.0 torchvision===0.4.1 -f https://download.pytorch.org/whl/torch_stable （default for CUDA10）

In [2]:
import torch
torch.__version__

'2.0.1+cu117'

### Basic usage method.

Creating a matrix, isn't it refreshing? Those who use TensorFlow might feel this way...

The "empty" function in PyTorch creates an uninitialized matrix. It does not automatically make it a matrix of zeros. 

The function simply allocates space for the matrix, but it does not fill the matrix with any values. 

Therefore, it could contain whatever values were already in the allocated memory.

In [3]:
x = torch.empty(5, 3)
x

tensor([[8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39],
        [9.7346e-39, 1.0745e-38, 1.0102e-38]])

In [31]:
# you can generate a matrix with random values
x = torch.rand(5, 3)
print(x,"\t",torch.mean(x))

tensor([[0.3129, 0.3408, 0.3647],
        [0.5079, 0.6317, 0.0058],
        [0.9295, 0.6210, 0.8737],
        [0.5311, 0.7273, 0.0632],
        [0.5192, 0.1410, 0.4368]]) 	 tensor(0.4671)


In [4]:
#  initialize a zero matrix in PyTorch quite simply
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
# create matrix with data inputted
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])


PyTorch's operations are indeed very similar to those provided by NumPy.

In [1]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

import torch
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
x = x.new_ones(5, 3, dtype=torch.double)      
print(x)

# with a tensor filled with random numbers from a normal distribution, and of type float
x = torch.randn_like(x, dtype=torch.float)    
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.2816,  0.9379,  1.9308],
        [-1.1799, -0.2935,  0.3151],
        [-1.0946, -0.5954,  0.5812],
        [ 1.1416,  0.3710,  1.0491],
        [-0.3238, -0.2913,  0.9558]])


In [4]:
# Display matrix size
x.size()

torch.Size([5, 3])

### Basic calculation method

In [5]:
y = torch.rand(5, 3)
x + y

tensor([[ 3.1040,  1.4851,  2.4684],
        [-1.0300, -0.0917,  0.6337],
        [-0.7469,  0.3445,  1.4950],
        [ 1.7201,  1.2844,  2.0226],
        [ 0.5597,  0.5612,  1.4446]])

In [6]:
torch.add(x, y) #The addition is similar

tensor([[ 3.1040,  1.4851,  2.4684],
        [-1.0300, -0.0917,  0.6337],
        [-0.7469,  0.3445,  1.4950],
        [ 1.7201,  1.2844,  2.0226],
        [ 0.5597,  0.5612,  1.4446]])

### index

In [10]:
(x + y)[:, 1]

tensor([ 1.4851, -0.0917,  0.3445,  1.2844,  0.5612])

The `view` method in PyTorch is analogous to the reshape function in numpy. 

In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) 
print(x.size(), y.size(), z.size())
print(x,'\n',y,'\n',z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-2.9485,  0.4962, -1.5095,  0.8563],
        [-0.1792, -2.5895,  1.5814,  1.2070],
        [ 0.4675,  1.1906, -0.6261, -0.5230],
        [-0.5295, -1.0798,  1.3056,  0.0952]]) 
 tensor([-2.9485,  0.4962, -1.5095,  0.8563, -0.1792, -2.5895,  1.5814,  1.2070,
         0.4675,  1.1906, -0.6261, -0.5230, -0.5295, -1.0798,  1.3056,  0.0952]) 
 tensor([[-2.9485,  0.4962, -1.5095,  0.8563, -0.1792, -2.5895,  1.5814,  1.2070],
        [ 0.4675,  1.1906, -0.6261, -0.5230, -0.5295, -1.0798,  1.3056,  0.0952]])


### PyTorch can easily work together with NumPy. 

You can convert a PyTorch Tensor to a NumPy array and vice versa

In [13]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)