### Common forms of Tensor

* 0: scalar
* 1: vector
* 2: matrix
* 3: n-dimensional tensor

In [5]:
pip show torch

Name: torch
Version: 2.0.1+cu117
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: f:\anaconda\envs\onekey\lib\site-packages
Requires: filelock, jinja2, networkx, sympy, typing-extensions
Required-by: cell2location, lightning, pymde, pyro-ppl, pytorch-lightning, scvi-tools, SpaGCN, torchaudio, torchmetrics, torchvision
Note: you may need to restart the kernel to use updated packages.


In [1]:
import torch
from torch import tensor

### Scalar

通常就是一个数值

In [2]:
x = tensor(42.)
x

tensor(42.)

In [3]:
x.dim()

0

In [4]:
2 * x

tensor(84.)

In [6]:
x.item()

42.0

## Vector

For example: `[-5., 2., 0.]`, which in deep learning usually refers to features, 

e.g., word vector features, features of a certain dimension, etc.
$$\vec{v} = \left[ v_1, v_2, \ldots, v_n \right]$$

In [7]:
v = tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [8]:
v.dim()

1

In [9]:
v.size()

torch.Size([3])

### Matrix
- The general computations are matrices, which are usually multidimensional

In [10]:
M = tensor([[1., 2.], [3., 4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [11]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [15]:
tensor([1., 0.]).matmul(M)

tensor([1., 2.])

In [14]:
M * M

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [13]:
tensor([1., 2.]).matmul(M)

tensor([ 7., 10.])

## Tensor with different shapes

![Scalar, vector, matrix, tensor - a drawing by Tai-Danae Bradley](./figures/arraychart.jpg)